ladislav-zezula/CascLib

src/common/Common.h

This ensures `GetLastError` and `SetLastError` have C-linkage, in line with [their declaration in StormLib](https://github.com/ladislav-zezula/StormLib/blob/58166d6ba7fa1bc76b2569b9f03d9e4a1642e416/src/StormLib.h#L1072-L1080).
I'm not sure if anything else in that file should be externed in addition.

Expose error functions

---

.gitignore

Versions 1.7.0 and later of `git` contain an annoying change in the behavior of `git submodule`.
Submodules are now regarded as **dirty** if they have any modified files or untracked files, whereas previously it would only be the case if HEAD in the submodule pointed to the wrong commit.
When building and creating an application using **CascLib** as a `git submodule`, it flags the repo as **dirty** because of the `Makefile`.
This change adds the `Makefile` to `.gitignore` next to the rest of the CMake files.

Ignore Makefile to prevent git v1.7.0+ "feature"

---

src/CascFiles.cpp

Happens when there are multiple builds defined in .build.info file and the first one is not active
(failing assertion pbData != NULL in debug mode)

Fixed memory leaks in ParseFile_BuildInfo

---

src/CascFiles.cpp

The second line of my .build.info for Diablo 3 is 636 characters long, after installing all language packs.

Support for longer .build.info lines

---

src/CascRootFile_WoW6.cpp

To use a binary search in array, the array must be sorted - created FileDataIdLookupTable as array of PCASC_FILE_ENTRY, this is much faster than sorting FileTable (nice qsort_pointer_array btw) and having to delay insertion into `pRootMap` because of elements being swapped around
Fixed calculating FileDataId, the index in loop restarts from 0 for every root entry, removed unneeded counter for FileDataId from TRootHandler_WoW6
Also renamed two previously unknown arguments to ParseWowRootFile based on client code from build 7.0.3.22210
Fixes #45

Fixed opening files by FileDataId (WoW only)

---

src/common/FileStream.cpp

If calling fstat64 in BaseFile_Open fails then opened file handle is not assigned to `pStream->Base.File.hFile` field, causing the handle to not be closed in BaseFile_Close leaking it.

Fix leaked handle in case calling fstat64 fails when trying to open file

---

src/common/FileStream.cpp
src/common/ListFile.cpp
src/common/Map.cpp

Handle lseek64 failure
Fix possible null dereference
Found when running coverity on TrinityCore

More static analysis fixes

---

.gitignore
src/CascPort.h
src/common/FileStream.cpp

Fixes closing file descriptor 0 (/dev/tty1 on my system or one of casc storage files on subsequent CascOpenStorage calls) causing file operations to randomly fail when accessing a closed data.xxx file

Linux closing file descriptor 0

---

src/CascRootFile_Diablo3.cpp
src/CascRootFile_WoW6.cpp
src/common/RootHandler.cpp

Currently the lib doesn't compile on Mac/Linux because one .cpp file uses the macro ` UNREFERENCED_PARAMETER` which is only defined on Windows. Fixed by using CASCLIB_UNUSED. Also removed 2 warnings due to casting NULL to DWORD.
The lib now compiles and works correctly (tested on Mac OS X with HOTS).

Fix build on Mac/Linux

---

CMakeLists.txt
src/CascPort.h
src/CascRootFile_SC1.cpp

- Added CascRootFile_SC1.cpp to CMakeLists.txt
- Added LPSTR definition to CascPort.h
- Added support for search mask to CascRootFile_SC1.cpp

Non-windows fixes & SC1 search mask support

---

src/CascLib.h
src/CascOpenStorage.cpp

Expose parsed locale tags from .build.info
Some time ago something changed that CascOpenStorage no longer fails when given unavailable locale, instead it now allows operating on all files which are shared by all locales
This behavior is undesirable in the tool extracting all db2 files as it should either extract everything or nothing. Right now it extracts a partial set of files (these that don't have any localized strings in them) and this change allows me to filter out these locales

Add a way to get available locales from .build.info

---

src/CascPort.h

Using CascLib + WxWidgets in WoW Model Viewer fires me some warnings about _CRT_SECURE_NO_DEPRECATE & _CRT_NON_CONFORMING_SWPRINTFS already defined.
As wxWidgets also define those (as of you, to avoid MSCV8.0 warning), I assume it is better to enclose them in #ifndef statements.

Enclose some #define in #ifndef statements

---

src/CascRootFile_SC1.cpp

Some unused variables (probalby due to copy paste when creating CascRootFile_SC1) triggers some warnings. Simply remove them

Remove compilation warnings

---

CMakeLists.txt

Apple target - Make sure the "set target properties" are being set for the correct target based on "shared" or "static" option

When APPLE is defined, make sure to set target properties to the relevant target

---

CMakeLists.txt

Currently, the CMakeLists.txt file doesn't provide the targets _casc_ and _casc_static_ with the INTERFACE_INCLUDE_DIRECTORES property, however, a small call to _target_include_directories()_ fixes this issue, making the project much easier to be included when being compiled from sources.

Added include directories for CMake targets

---

src/CascDecrypt.cpp
src/CascLib.h

My use case for this will be editing db2 file headers to erase known key names to simplify reading db2 files after they have been extracted out of casc storage

Add CascFindEncryptionKey to public api

---

src/CascLib.h

At TrinityCore we build CascLib from source using our own simplified CMakeLists.txt so every time I upgrade the lib I need to rip out these #pragma comment statements (because lib name is always casc.lib)
This change simplifies my upgrade process

Allow excluding #pragma comment for windows cmake users

---

src/CascCommon.h
src/CascFiles.cpp
src/CascLib.def
src/CascLib.h
src/CascOpenStorage.cpp
src/common/Common.h

World of Warcraft supports installing multiple products into the same directory to minimize disk usage
.build.info for such configuration looks like this
```
Branch!STRING:0|Active!DEC:1|Build Key!HEX:16|CDN Key!HEX:16|Install Key!HEX:16|IM Size!DEC:4|CDN Path!STRING:0|CDN Hosts!STRING:0|CDN Servers!STRING:0|Tags!STRING:0|Armadillo!STRING:0|Last Activated!STRING:0|Version!STRING:0|Product!STRING:0|Build Complete!DEC:1
eu|1|d3192b18729bb6f00c595fd37097c19f|3bb4ba6bf2d4c855639247abf80fd6aa|8bafcfcf55c7933486336bef35aa2d3f||tpr/wow|eu.cdn.blizzard.com level3.blizzard.com|http://eu.cdn.blizzard.com/?maxhosts=4 http://level3.blizzard.com/?maxhosts=4 https://blzddist1-a.akamaihd.net/?fallback=1&maxhosts=4 https://eu.cdn.blizzard.com/?fallback=1&maxhosts=4 …
```

Allow selecting which installed product to open storage for

---

src/CascPort.h

Fix mac build. Probably. (no mac to test, mac vms are a pain too)
This include is needed for `isxdigit` here
https://github.com/ladislav-zezula/CascLib/blob/57a26ab26ff23d07e870044c4971d7a51488e9d6/src/CascFiles.cpp#L161

Fix mac build

---

src/CascRootFile_TVFS.cpp

ULONG is not defined with Clang on Ubuntu. The function InsertUnknownCKeyEntry is called with CASC_CKEY_ENTRY.ContentSize as last parameter, which is DWORD. Thus the change

Restore compilation under Linux

---

src/CascPort.h

These small changes fix Mac compilation so that CascLib can be compiled by the [vcpkg](https://github.com/microsoft/vcpkg/) Mac environment.

Fix Mac compilation

---

src/CascOpenStorage.cpp

I believe f3cb5f10dd4290a1649ac815fdc270ed0827a6e8 is the commit that broke loading all locale-specific files (didn't try to bisect, I upgraded from b91f87c770c78340dcd96df970e55b5c0469e884 to 8130478a7918350e2fbdb7c5a0723a700820b1cb)
Original code is the locale mask to 0 when proper locales are given to CascOpenStorage, resulting in none of the locale-specific files being available for reading

Fix loading locale specific files

---

test/CascTest.cpp

Fix https://github.com/ladislav-zezula/CascLib/issues/173

Fix error: 'UNREFERENCED_PARAMETER' was not declared in this scope

---

src/CascPort.h

This PR fixed build errors on macOS Catalina:
```
/Users/fluxxu/Projects/CascLib/src/CascReadFile.cpp:44:9: Use of undeclared identifier 'pthread_mutex_lock'
/Users/fluxxu/Projects/CascLib/src/CascReadFile.cpp:60:9: Use of undeclared identifier 'pthread_mutex_unlock'
```

Fix macOS build.

---

CMakeLists.txt

When `CASC_BUILD_STATIC_LIB` is set, build should output `libcasc.a` instead of `casc.framework`.

Fix macOS static build.

---

.gitignore
CMakeLists.txt
src/CascDumpData.cpp
src/CascReadFile.cpp
src/common/Common.cpp
src/common/Common.h
src/common/Mime.cpp

- remove warning in cmake, bump version to something reasonable modern
- remove warning about zero symbols in CascDumpData
- remove of using va_arg in CombinePath, using std::initializer_list instead
- remove warning in two switches about missing case

remove warnings on mac

---

CascLib_vs19.vcxproj
CascLib_vs19_dll.vcxproj
CascLib_vs19_test.vcxproj

Upgrade toolset to v142 for VS19 projects.
Setting the Window SDK platform to "10.0" without subsversion allows to take the latest installed version.

Upgrade toolset v142 and set SDK 10.0 for VS19

---

CMakeLists.txt
src/CascPort.h
src/common/Common.cpp
src/common/Directory.cpp
src/common/FileStream.cpp
src/common/Sockets.cpp
test/CascTest.cpp

* Prefix PLATFORM_ definitions with CASCLIB_ to avoid possible conflicts 
* Remove bzip2 references
* Only define __SYS_ZLIB if not defined earlier

Preprocessor cleanup

---

src/DllMain.def

CascLib started using its own GetError and SetError functions to preserve compatibility with platforms that don't define GetLastError and SetLastError, but this change was not reflected in the dll exports so linking of apps that use them fails. This PR fixes that (tested in vcpkg as master doesn't seem to use the def file anymore, vcpkg patches it back in).

Update Dll definitions

---

src/common/Csv.cpp

In c7a2b8ce75f52ddb450fec7bcfd3c760d2f9e0be I changed destruction of m_szCsvFile because of how it was allocated in LoadFileToMemory(), but I missed another allocation of it.

Don't mix C and C++ memory allocations (part 2)

---

src/common/FileTree.cpp

The FileDataId is a uint32 and can store data until 4294967295.

Extend FileDataId sanity check

---

src/CascOpenStorage.cpp

Replace SetLastError call to SetCascError as SetLastError is a Microsoft Windows-specific system API call.

CascOpenStorage.cpp | fix builds on non-windows

---

CascLib_vs22.vcxproj
CascLib_vs22_dll.vcxproj
CascLib_vs22_test.vcxproj
src/CascFiles.cpp

This fixes opening storages when users manually create a subdirectory that resembles valid DataDir
For example
Root: `/home/ubuntu/World of Warcraft`
DataDir: `/home/ubuntu/World of Warcraft/Data`
Broken user dir: `/home/ubuntu/World of Warcraft/data` <- existence of this dir causes opening storage to fail

Fix data dir confusion

---

src/CascCommon.h
src/CascDumpData.cpp
src/CascOpenStorage.cpp
src/CascReadFile.cpp
src/CascRootFile_MNDX.cpp
src/CascRootFile_WoW.cpp
src/common/Array.h
src/common/ArraySparse.h
src/common/FileTree.h
src/common/Mime.cpp
src/common/Mime.h

Some of this debug code makes casclib unusable by other projects when compiled in debug mode (__debugbreak() on specific fileid)
My code uses cmake to generate all project files so if i want to build my code in debug mode, casclib also has to be built in debug mode (even if that wasnt a requirement, mixing debug and release CRT is not a good idea)
Because _DEBUG cannot be undefined (its enforced when compiling with debug CRT), this PR replaces its usage with a new macro that can be undefined by users

Replace usages of predefined macro _DEBUG with CASCLIB_DEBUG

---

CMakeLists.txt

Adds the new overwatch files to cmake so we don't get linker errors.
Fixes these errors:
```
3>casc.lib(CascRootFile_OW.obj) : error LNK2019: unresolved external symbol "unsigned long __cdecl LoadApplicationPackageManifestFile(struct TCascStorage *,class CASC_FILE_TREE &,struct CASC_CKEY_ENTRY *,char const *)" (?LoadApplicationPackageManifestFile@@YAKPEAUTCascStorage@@AEAVCASC_FILE_TREE@@PEAUCASC_CKEY_ENTRY@@PEBD@Z) referenced in function "public: unsigned long __cdecl TRootHandler_OW::Load(struct TCascStorage *,class CASC_CSV &,unsigned __int64,unsigned __int64)" (?Load@TRootHandler_OW@@QEAAKPEAUTCascStorage@@AEAVCASC_CSV@@_K2@Z)
3>casc.lib(CascRootFile_OW.obj) : error LNK2019: unresolved external symbol "unsigned long __cdecl LoadContentManifestFile(struct TCascStorage *,class …
```

Add missing overwatch source files to cmake

---

src/CascRootFile_TVFS.cpp
src/CascStructs.h

This part of the change comes from [Scobalula](https://github.com/Scobalula).
I submitted it on his behalf.
Problem:
Basically when casc patches certain installations, it creates more than 256 data files.
It's why certain people experienced crashes when this happens.
As for the span array, He experienced this during the beta of Bocw and so many others did, span array goes above 256 and casclib doesn't check and just blindly reallocated the array.
[test.txt](https://github.com/ladislav-zezula/CascLib/files/13775736/test.txt)
This can happen during a heavily patched installation and when battlenet says "playable" while still updating.
In Call of Duty, it can be as (.xsub/.xpak) files are all over the place with potentially >1GB file size so multiple file spans.

Increase pre-allocated Casc table sizes to address crashing

---

src/CascCommon.h
src/CascLib.h
src/CascOpenFile.cpp
src/CascReadFile.cpp
src/CascRootFile_OW.cpp
src/common/FileTree.cpp
src/common/FileTree.h
src/common/RootHandler.cpp
src/common/RootHandler.h

Enhanced file caching and handling in CASC library
- **Modified CascCommon.h**: 
- Added `CascCacheWholeFile` strategy in `CSTRTG` enum.
- **Updated CascLib.h**: 
- Defined `CASC_CACHE_WHOLE_FILE` flag.
- Declared new functions: `CascSetCacheStrategy` and `CascGetFileId`.
- **Implemented in CascOpenFile.cpp**:
- Added `CascSetCacheStrategy` function to set cache strategy.
- Added `CascGetFileId` function to retrieve file ID by name.
- **Enhanced ReadFile performance in CascReadFile.cpp**:
- Implemented `ReadFile_WholeCached` function for whole file caching.
- Optimized decoded buffer handling.
- Fixed rare invalid read issue.
- **Improved CKeyEntry handling in FileTree.cpp and FileTree.h**:
- Supported multiple keys in file nodes.
- Enhanced insertion and retrieval methods for file nodes. …

* Enhanced file caching and handling in CASC library

---

src/common/Common.cpp

Make the variable thread local, similar to how GetLastError from windows api works

Make GetCascError/SetCascError threadsafe on linux
